// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tbvszyxrrtqorwnionfv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRidnN6eXhycnRxb3J3bmlvbmZ2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY1MjIwMjYsImV4cCI6MjA1MjA5ODAyNn0.WnzWIMESNQvFxiApgD-qUUzo3L2BUfbPGtmJZ0Dca_Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);